### ISSUE TITLE
Error running unused, invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by stoivo** [joshuaclayton/unused#72] opened 2016-08-30 09:15 UTC
This might be me doing something stupid

``` bash
ctags -R .
unused
Unused: analyzing unused: ./tags: hGetContents: invalid argument (invalid byte sequence)
```

Any idea of what doing wrong?

**Comment by joshuaclayton** [comment] 2016-08-30 12:10
@stoivo

> This might be me doing something stupid

Nope, this should work correctly!

> Any idea of what doing wrong?

It looks like `unused` is having trouble reading your `./tags` file. Would it be possible to share it somehow?

**Comment by stoile** [comment] 2016-08-30 15:30
Same problem here, but I cannot share the tags file. Is there a way to find out which entry/line in the tags file is causing the problem?

**Comment by joshuaclayton** [comment] 2016-08-30 17:36
@stoile we might be possible to narrow down to what type of data is causing the problem; can you run:

```sh
cat .git/tags | cut -f1 | unused --stdin 
```

And let me know what happens? My guess is that it's some sort of strange encoding character that's causing problems, but lack of access to the tags makes it difficult for me to reproduce. If the above command *does* work, it's an indicator that it's either in the path, function definition, or type columns, which we can hopefully use to narrow things down.

@stoile @stoivo can you also report the path for ctags (`which ctags`) and the version (`ctags --version`)?

**Comment by stoile** [comment] 2016-08-31 07:03
`$ which ctags
/usr/bin/ctags
$ ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jun  9 2014, 21:59:46
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)`

I get the same error when running your command with `cut -f 1` and I did kind of a bisect. I'll try to attach a tags file with the line that causes the problem.

**Comment by stoile** [comment] 2016-08-31 08:59
@joshuaclayton I'll try to create a test case for you as soon as I find the time.

It looks like the problem is as follows: I am working with C# files created with Visual Studio 2015 on Windows. The files are in an svn repository and checked out on a CentOS Linux machine where I play around with unused. We have comments (and also had one symbol) with german umlauts (ä. ö, ü) and this seems to be the problem. It might be possible to reporoduce this without Windows, Visual Studio and svn, but I don't have the time just now.

BTW, the german umlaut in the symbol was a typo. So unused already fixed one bug for us without even doing what it's supposed to do.

**Comment by stoile** [comment] 2016-08-31 11:16
@joshuaclayton Some more information: Our code base is already some years old. Some files are encoded in ISO-8859-something, some newer files are encoded in UTF-8. Which seems to be no problem so far, because each file is handled individually and the encodign is detected. But ctags seems to merge all files (or information from all files) into one file, which has a mixed encoding afterwards. Does that sound plausible?

I'm not sure if unused can do anything about this or if this is even a bug/issue. For us the best way seems to be to convert our code base to UTF-8 and try again.

**Comment by joshuaclayton** [comment] 2016-08-31 14:40
@stoile fascinating; the multiple encodings aspect might be the cause of it. I'm unfamiliar with the inner-workings of ctags, but if it normalizes on an encoding that's not UTF-8, it's likely the cause.

With this encoding information, I may be able to reproduce. If I can, I'll follow up here. Thanks for the context!

**Comment by stoivo** [comment] 2016-08-31 19:58
when my ctag file contain and is saved with Windows 1252
```ctag
jgrid.defaults	public/javascripts/js/i18n/grid.locale-it.js	/^(function(a){a.jgrid={edit:{nodefined:"è"}}})(jQuery);/;"	p
```
I get the error.

If i open the file tags in sublime and `Save with UTF-8` is works.

**Comment by DmitryBochkarev** [comment] 2016-09-12 11:08
i have same issue with standard ctags, https://github.com/universal-ctags/ctags fixed this for me

**Comment by joshuaclayton** [comment] 2016-10-14 10:16
After further digging into character encodings and default behavior with Haskell, I think the only truly reliable way to proceed would be to have a requirement of UTF-8 for the generated ctags file. I've verified that `ag` will handle non-UTF-8 files, although rendering output of matches is dependent on `$LANG`.

How this can be manifested into an improvement within `unused`, I believe, is better error messaging around reading the tags file with subsequent failure, to help guide users towards better tooling (thanks @DmitryBochkarev, I'm going to check out Universal Ctags today!) and courses of action when the encoding doesn't line up.

**Comment by joshuaclayton** [comment] 2020-05-05 06:12
Closing this, as a rewrite is in the works, which recommends Universal Ctags moving forward.

**Closed by joshuaclayton** 2020-05-05 06:12 UTC
